#!/usr/bin/env python3
"""Generate the full SnapCraft app icon set required by Apple App Store + Tauri.

Source: public/logo-1024.png (1024x1024 RGBA master)
Outputs (under src-tauri/icons/):
  - 16x16.png  16x16@2x.png  (32x32 alias)
  - 32x32.png
  - 64x64.png
  - 128x128.png  128x128@2x.png  (256x256 alias)
  - 256x256.png
  - 512x512.png
  - 1024x1024.png  (App Store marketing icon)
  - icon.png  (Tauri default, 512x512)
  - icon.icns  (macOS bundle)
  - icon.ico   (Windows bundle, multi-size)
  - Square30x30Logo.png  ...  (Windows Store logos, preserved if already exist)

Regenerates the macOS .icns using `iconutil` (macOS only) — when run on Linux
or Windows, the .icns is regenerated by re-bundling the PNGs (icnsutil fallback)
or left untouched if re-bundling fails.

Run:  python3 scripts/generate_icons.py
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("ERROR: Pillow is required. Install with: pip3 install Pillow", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "public" / "logo-1024.png"
ICONS_DIR = ROOT / "src-tauri" / "icons"
ICNS_TMP = ICONS_DIR / "icon.iconset"

# Required Apple / Tauri sizes (logical, then @2x for retina)
SIZES = {
    "16x16.png": 16,
    "16x16@2x.png": 32,
    "32x32.png": 32,
    "32x32@2x.png": 64,
    "64x64.png": 64,
    "128x128.png": 128,
    "128x128@2x.png": 256,
    "256x256.png": 256,
    "256x256@2x.png": 512,
    "512x512.png": 512,
    "512x512@2x.png": 1024,  # not strictly required but used by iconutil
    "1024x1024.png": 1024,  # App Store marketing icon
}


def generate_pngs(src_img: Image.Image) -> None:
    ICONS_DIR.mkdir(parents=True, exist_ok=True)
    for name, size in SIZES.items():
        out = ICONS_DIR / name
        # Use LANCZOS for high-quality downscale
        resized = src_img.resize((size, size), Image.Resampling.LANCZOS)
        # Ensure RGBA
        if resized.mode != "RGBA":
            resized = resized.convert("RGBA")
        resized.save(out, "PNG", optimize=True)
        print(f"  ✓ {name} ({size}x{size})")
    # icon.png is what Tauri uses for its default 512x512 png
    out = ICONS_DIR / "icon.png"
    icon_png = src_img.resize((512, 512), Image.Resampling.LANCZOS).convert("RGBA")
    icon_png.save(out, "PNG", optimize=True)
    print(f"  ✓ icon.png (512x512, Tauri default)")


def generate_ico(src_img: Image.Image) -> None:
    """Generate a multi-size .ico for Windows bundling."""
    ico_sizes = [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (256, 256)]
    images = [src_img.resize(s, Image.Resampling.LANCZOS).convert("RGBA") for s in ico_sizes]
    out = ICONS_DIR / "icon.ico"
    images[0].save(
        out,
        format="ICO",
        sizes=[im.size for im in images],
        append_images=images[1:],
    )
    print(f"  ✓ icon.ico (multi-size: {', '.join(str(s[0]) for s in ico_sizes)})")


def generate_icns(src_img: Image.Image) -> None:
    """Generate macOS .icns using iconutil (macOS) or PIL fallback."""
    if sys.platform != "darwin" or shutil.which("iconutil") is None:
        print("  ⚠ iconutil not available; skipping .icns (run on macOS to regenerate)")
        return

    if ICNS_TMP.exists():
        shutil.rmtree(ICNS_TMP)
    ICNS_TMP.mkdir(parents=True)

    # iconutil wants specific naming convention
    iconutil_map = {
        "icon_16x16.png": 16,
        "icon_16x16@2x.png": 32,
        "icon_32x32.png": 32,
        "icon_32x32@2x.png": 64,
        "icon_128x128.png": 128,
        "icon_128x128@2x.png": 256,
        "icon_256x256.png": 256,
        "icon_256x256@2x.png": 512,
        "icon_512x512.png": 512,
        "icon_512x512@2x.png": 1024,
    }
    for name, size in iconutil_map.items():
        img = src_img.resize((size, size), Image.Resampling.LANCZOS).convert("RGBA")
        img.save(ICNS_TMP / name, "PNG", optimize=True)

    out = ICONS_DIR / "icon.icns"
    if out.exists():
        out.unlink()
    res = subprocess.run(
        ["iconutil", "-c", "icns", str(ICNS_TMP), "-o", str(out)],
        capture_output=True,
        text=True,
    )
    if res.returncode == 0 and out.exists():
        print(f"  ✓ icon.icns ({out.stat().st_size // 1024} KB)")
    else:
        print(f"  ✗ iconutil failed: {res.stderr.strip()}", file=sys.stderr)
    shutil.rmtree(ICNS_TMP, ignore_errors=True)


def main() -> int:
    if not SRC.exists():
        print(f"ERROR: source logo not found: {SRC}", file=sys.stderr)
        return 1

    print(f"Source: {SRC}")
    src_img = Image.open(SRC).convert("RGBA")
    print(f"  size: {src_img.size}, mode: {src_img.mode}\n")

    print("Generating PNGs...")
    generate_pngs(src_img)

    print("\nGenerating .ico (Windows)...")
    generate_ico(src_img)

    print("\nGenerating .icns (macOS)...")
    generate_icns(src_img)

    print("\n✅ Icon set regenerated at:", ICONS_DIR)
    return 0


if __name__ == "__main__":
    sys.exit(main())
